import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";

import { ActionButton, AppScreen, NumericField, palette, Section, TextField } from "@/components/guyvs/ui";
import { makeArena, uid } from "@/lib/guyvs/defaults";
import { useProject } from "@/lib/guyvs/project-store";

export default function ArenasScreen() {
  const { state, addArena, replaceArena } = useProject();
  const [selectedId, setSelectedId] = useState(state.project.arenas[0]?.id ?? "");
  const [draftPoints, setDraftPoints] = useState<{ x: number; y: number }[]>([]);
  useEffect(() => { if (!state.project.arenas.some((arena) => arena.id === selectedId)) setSelectedId(state.project.arenas[0]?.id ?? ""); }, [selectedId, state.project.arenas]);
  const arena = state.project.arenas.find((item) => item.id === selectedId);
  const update = (patch: Partial<typeof arena>) => arena && replaceArena({ ...arena, ...patch });
  return <AppScreen><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.title}>Arena Creator</Text><Text style={styles.subtitle}>Draw rings, place shapes, tune bounce, and stack local physics zones.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{state.project.arenas.map((item) => <ActionButton key={item.id} label={item.name} tone={item.id === selectedId ? "magenta" : "ghost"} small onPress={() => setSelectedId(item.id)} />)}<ActionButton label="+" tone="cyan" small onPress={() => { const created = makeArena(); addArena(created); setSelectedId(created.id); }} /></ScrollView>
    {arena ? <>
      <Section title="Arena settings" subtitle="These values affect every active combatant during the battle simulation."><TextField value={arena.name} onChangeText={(name) => update({ name })} placeholder="Arena name" /><TextField value={arena.background} onChangeText={(background) => update({ background })} placeholder="#111827" autoCapitalize="characters" /><NumericField label="Gravity" value={arena.gravity} step={20} min={0} max={5000} onChange={(gravity) => update({ gravity })} /></Section>
      <Section title="Ring & collision shapes" subtitle="Shape data is saved as editable geometry; use presets or build a custom collision boundary below.">{arena.shapes.map((shape) => <View key={shape.id} style={styles.row}><View style={[styles.shapeIcon, { borderColor: shape.color }]} /><View style={styles.flex}><Text style={styles.itemTitle}>{shape.type.toUpperCase()} boundary</Text><Text style={styles.itemMeta}>{shape.points.length ? `${shape.points.length} custom points · ` : ""}{shape.size.x}×{shape.size.y} · {Math.round(shape.bounce * 100)}% bounce</Text></View><ActionButton label="−" tone="danger" small onPress={() => update({ shapes: arena.shapes.filter((item) => item.id !== shape.id) })} /></View>)}<View style={styles.presetRow}><ActionButton label="Circle" tone="ghost" small onPress={() => update({ shapes: [...arena.shapes, { id: uid("shape"), type: "circle", points: [], position: { x: 180, y: 210 }, size: { x: 180, y: 180 }, rotation: 0, bounce: 0.85, friction: 0.25, color: "#22D3EE" }] })} /><ActionButton label="Triangle" tone="ghost" small onPress={() => update({ shapes: [...arena.shapes, { id: uid("shape"), type: "triangle", points: [{ x: 0, y: 180 }, { x: 160, y: 0 }, { x: 320, y: 180 }], position: { x: 0, y: 130 }, size: { x: 320, y: 180 }, rotation: 0, bounce: 0.9, friction: 0.25, color: "#F472B6" }] })} /><ActionButton label="Platform" tone="ghost" small onPress={() => update({ shapes: [...arena.shapes, { id: uid("shape"), type: "rectangle", points: [], position: { x: 180, y: 240 }, size: { x: 120, y: 28 }, rotation: 0, bounce: 0.7, friction: 0.4, color: "#F472B6" }] })} /></View></Section>
      <Section title="Custom shape ring" subtitle="Tap the canvas to place points in the boundary, then convert them into a reusable polygon. This keeps your raw geometry editable rather than rasterizing it."><View style={styles.drawCanvas} onStartShouldSetResponder={() => true} onResponderRelease={(event) => setDraftPoints((points) => [...points, { x: Math.round(event.nativeEvent.locationX), y: Math.round(event.nativeEvent.locationY) }])}>{draftPoints.map((point, index) => <View key={`${point.x}-${point.y}-${index}`} style={[styles.point, { left: point.x - 5, top: point.y - 5 }]} />)}<Text style={styles.canvasHint}>{draftPoints.length ? `${draftPoints.length} points captured` : "Tap to trace a custom boundary"}</Text></View><View style={styles.presetRow}><ActionButton label="Clear" tone="ghost" small onPress={() => setDraftPoints([])} /><ActionButton label="Make custom ring" tone="magenta" small disabled={draftPoints.length < 3} onPress={() => { update({ shapes: [...arena.shapes, { id: uid("shape"), type: "polygon", points: draftPoints, position: { x: 0, y: 0 }, size: { x: 320, y: 210 }, rotation: 0, bounce: 0.88, friction: 0.3, color: "#A3E635" }] }); setDraftPoints([]); }} /></View></Section>
      <Section title="Physics zones" subtitle="Zones are functional local modifiers ready for the battle lab.">{arena.zones.map((zone) => <View key={zone.id} style={styles.row}><View style={[styles.zoneIcon, { backgroundColor: zone.color }]} /><View style={styles.flex}><Text style={styles.itemTitle}>{zone.type}</Text><Text style={styles.itemMeta}>{zone.size.x}×{zone.size.y} · strength {zone.strength}</Text></View><ActionButton label="−" tone="danger" small onPress={() => update({ zones: arena.zones.filter((item) => item.id !== zone.id) })} /></View>)}<ActionButton label="Add bounce zone" tone="lime" onPress={() => update({ zones: [...arena.zones, { id: uid("zone"), type: "bounce", position: { x: 180, y: 250 }, size: { x: 110, y: 56 }, strength: 1.2, color: "#A3E635" }] })} /></Section>
    </> : <Section title="No arenas" subtitle="Create an editable arena to begin."><ActionButton label="Create Arena" onPress={() => addArena(makeArena())} /></Section>}
  </ScrollView></AppScreen>;
}

const styles = StyleSheet.create({ content: { padding: 18, gap: 16, paddingBottom: 32 }, title: { color: palette.text, fontSize: 30, fontWeight: "900", letterSpacing: -0.8 }, subtitle: { color: palette.muted, marginTop: -8, fontSize: 14, lineHeight: 20 }, chips: { gap: 8, paddingVertical: 2 }, row: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: palette.panelRaised, borderRadius: 12, padding: 10 }, flex: { flex: 1, gap: 2 }, shapeIcon: { width: 23, height: 23, borderWidth: 3, borderRadius: 6 }, zoneIcon: { width: 23, height: 23, borderRadius: 7 }, itemTitle: { color: palette.text, fontSize: 13, fontWeight: "800" }, itemMeta: { color: palette.muted, fontSize: 11 }, presetRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, drawCanvas: { height: 210, borderRadius: 14, backgroundColor: palette.ink, borderWidth: 1, borderColor: palette.border, overflow: "hidden", position: "relative" }, point: { position: "absolute", width: 10, height: 10, borderRadius: 5, backgroundColor: palette.lime }, canvasHint: { color: palette.muted, fontSize: 12, alignSelf: "center", marginTop: 95 }, });
