import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";

import { aiActions, aiConditions, abilityTypes, nextValue } from "@/lib/guyvs/combat-constants";
import { uid } from "@/lib/guyvs/defaults";
import { useProject } from "@/lib/guyvs/project-store";
import { ActionButton, AppScreen, NumericField, palette, Section, TextField } from "@/components/guyvs/ui";

export default function CombatScreen() {
  const { state, replaceGuy } = useProject();
  const [selectedId, setSelectedId] = useState(state.project.guys[0]?.id ?? "");
  useEffect(() => { if (!state.project.guys.some((guy) => guy.id === selectedId)) setSelectedId(state.project.guys[0]?.id ?? ""); }, [selectedId, state.project.guys]);
  const guy = state.project.guys.find((item) => item.id === selectedId);
  const update = (patch: Partial<NonNullable<typeof guy>>) => guy && replaceGuy({ ...guy, ...patch });
  if (!guy) return <AppScreen><View style={styles.empty}><Text style={styles.emptyText}>Create a Guy before building combat assets.</Text></View></AppScreen>;
  const attacks = guy.attacks;
  const abilities = guy.abilities;
  const rules = guy.ai;
  const animations = guy.animations ?? [];
  const effects = guy.effects ?? [];
  const attack = attacks[0]; const ability = abilities[0]; const rule = rules[0]; const animation = animations[0]; const effect = effects[0];
  return <AppScreen><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.title}>Combat Studio</Text><Text style={styles.subtitle}>Every combat component is a reusable, editable asset attached to the selected Guy.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{state.project.guys.map((item) => <ActionButton key={item.id} label={item.name} tone={item.id === selectedId ? "magenta" : "ghost"} small onPress={() => setSelectedId(item.id)} />)}</ScrollView>
    <Section title="Attack timeline" subtitle="Windup → active frames → recovery. Each attack carries damage, knockback, and cooldown values.">
      {attack ? <><TextField value={attack.name} onChangeText={(name) => update({ attacks: attacks.map((item, index) => index === 0 ? { ...item, name } : item) })} /><NumericField label="Damage" value={attack.damage} step={1} min={0} max={999} onChange={(damage) => update({ attacks: attacks.map((item, index) => index === 0 ? { ...item, damage } : item) })} /><NumericField label="Knockback" value={attack.knockback} step={10} min={0} max={5000} onChange={(knockback) => update({ attacks: attacks.map((item, index) => index === 0 ? { ...item, knockback } : item) })} /><NumericField label="Cooldown (ms)" value={Math.round(attack.cooldown * 1000)} step={50} min={0} max={20000} onChange={(cooldown) => update({ attacks: attacks.map((item, index) => index === 0 ? { ...item, cooldown: cooldown / 1000 } : item) })} /><View style={styles.row}><StatChip label="Windup" value={`${Math.round(attack.windup * 1000)}ms`} /><StatChip label="Active" value={`${Math.round(attack.active * 1000)}ms`} /><StatChip label="Recovery" value={`${Math.round(attack.recovery * 1000)}ms`} /></View></> : null}
      <ActionButton label="Add attack" tone="magenta" onPress={() => update({ attacks: [...attacks, { id: uid("attack"), name: `Attack ${attacks.length + 1}`, damage: 6, knockback: 280, cooldown: 0.6, windup: 0.1, active: 0.12, recovery: 0.3, color: "#F472B6" }] })} />
    </Section>
    <Section title="Ability components" subtitle="Use dash, projectile, shockwave, shield, and force components with independent power and duration.">
      {ability ? <><TextField value={ability.name} onChangeText={(name) => update({ abilities: abilities.map((item, index) => index === 0 ? { ...item, name } : item) })} /><View style={styles.row}><Text style={styles.label}>Component: {ability.type}</Text><ActionButton label="Cycle type" tone="ghost" small onPress={() => update({ abilities: abilities.map((item, index) => index === 0 ? { ...item, type: nextValue(abilityTypes, item.type) } : item) })} /></View><NumericField label="Strength" value={ability.strength} step={20} min={0} max={5000} onChange={(strength) => update({ abilities: abilities.map((item, index) => index === 0 ? { ...item, strength } : item) })} /><NumericField label="Duration (ms)" value={Math.round(ability.duration * 1000)} step={50} min={0} max={20000} onChange={(duration) => update({ abilities: abilities.map((item, index) => index === 0 ? { ...item, duration: duration / 1000 } : item) })} /></> : null}
      <ActionButton label="Add ability" tone="lime" onPress={() => update({ abilities: [...abilities, { id: uid("ability"), name: `Ability ${abilities.length + 1}`, type: "projectile", cooldown: 2, strength: 320, duration: 0.8, color: "#A3E635" }] })} />
    </Section>
    <Section title="AI behavior graph" subtitle="A touch-friendly rule list models condition → action connections for the first AI layer.">
      {rule ? <><View style={styles.row}><Text style={styles.label}>IF {rule.condition}</Text><ActionButton label="Cycle condition" tone="ghost" small onPress={() => update({ ai: rules.map((item, index) => index === 0 ? { ...item, condition: nextValue(aiConditions, item.condition) } : item) })} /></View><View style={styles.row}><Text style={styles.label}>THEN {rule.action}</Text><ActionButton label="Cycle action" tone="ghost" small onPress={() => update({ ai: rules.map((item, index) => index === 0 ? { ...item, action: nextValue(aiActions, item.action) } : item) })} /></View><NumericField label="Threshold value" value={rule.value} step={5} min={0} max={9999} onChange={(value) => update({ ai: rules.map((item, index) => index === 0 ? { ...item, value } : item) })} /></> : null}
      <ActionButton label="Add AI rule" tone="cyan" onPress={() => update({ ai: [...rules, { id: uid("ai"), condition: "random", action: "wait", value: 50 }] })} />
    </Section>
    <Section title="Animation track" subtitle="Keyframe data is editable and can be reused by attacks and abilities.">{animation ? <><TextField value={animation.name} onChangeText={(name) => update({ animations: animations.map((item, index) => index === 0 ? { ...item, name } : item) })} /><NumericField label="Duration (ms)" value={Math.round(animation.duration * 1000)} step={100} min={100} max={20000} onChange={(duration) => update({ animations: animations.map((item, index) => index === 0 ? { ...item, duration: duration / 1000 } : item) })} /><Text style={styles.note}>{animation.keyframes.length} editable keyframes · looping {animation.loop ? "on" : "off"}</Text></> : null}<ActionButton label="Add animation" tone="ghost" onPress={() => update({ animations: [...animations, { id: uid("animation"), name: "New Motion", duration: 0.5, loop: false, keyframes: [{ time: 0, rotation: 0, scale: 1 }, { time: 0.5, rotation: 0, scale: 1 }] }] })} /></Section>
    <Section title="Visual effect" subtitle="Particle parameters are saved as an effect asset for impacts, trails, and ability events.">{effect ? <><TextField value={effect.name} onChangeText={(name) => update({ effects: effects.map((item, index) => index === 0 ? { ...item, name } : item) })} /><NumericField label="Particle count" value={effect.particleCount} step={1} min={0} max={500} onChange={(particleCount) => update({ effects: effects.map((item, index) => index === 0 ? { ...item, particleCount } : item) })} /><NumericField label="Speed" value={effect.speed} step={10} min={0} max={5000} onChange={(speed) => update({ effects: effects.map((item, index) => index === 0 ? { ...item, speed } : item) })} /></> : null}<ActionButton label="Add effect" tone="ghost" onPress={() => update({ effects: [...effects, { id: uid("effect"), name: "New Effect", particleCount: 12, lifetime: 0.4, speed: 180, color: guy.accent }] })} /></Section>
  </ScrollView></AppScreen>;
}

function StatChip({ label, value }: { label: string; value: string }) { return <View style={styles.chip}><Text style={styles.chipValue}>{value}</Text><Text style={styles.chipLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 18, gap: 16, paddingBottom: 32 }, title: { color: palette.text, fontSize: 30, fontWeight: "900", letterSpacing: -0.8 }, subtitle: { color: palette.muted, marginTop: -8, fontSize: 14, lineHeight: 20 }, chips: { gap: 8, paddingVertical: 2 }, row: { flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "space-between" }, label: { color: palette.text, fontSize: 13, fontWeight: "800", flex: 1 }, chip: { flex: 1, backgroundColor: palette.panelRaised, borderRadius: 12, padding: 10, gap: 3 }, chipValue: { color: palette.cyan, fontWeight: "900", fontSize: 13 }, chipLabel: { color: palette.muted, fontSize: 9, textTransform: "uppercase", letterSpacing: 0.5 }, note: { color: palette.muted, fontSize: 12 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 }, emptyText: { color: palette.muted, textAlign: "center" } });
